audit_header: false
title: East Valley Real Estate Video Blog with Aaron Dotterer
description: Our mission at The Dott Real Estate Group is to be your best resource for East Valley real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Dott Real Estate Group, your professional East Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Aaron Dotterer
  title:
  license_number:
  about_markdown: |
    Revelation Real Estate is the top producing brokerage in the East Valley for the last six years and one of the top companies in the state in production. We are one of the Top 10 Single Office Brokerages in the country named by the Wall Street Journal. 
  market: East Valley
  brand: The Dott Real Estate Group
  brokerage: Revelation Real Estate Group
  address: 2301 S Stearman Dr<br>Chandler, AZ 85286
  phone: 480-417-3417
  phone_type:
  phone2:
  phone2_type:
  email: Aaron@DottRealEstate.com
  url: http://www.DottRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.dottrealestate.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.dottrealestate.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your East Valley Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.dottrealestate.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a East Valley Home?"
    CTA_text2: "Search the entire MLS for your East Valley home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.dottrealestate.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/DottRealEstate/
  linkedin_url:
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UC2shrs2zGgRabw5D2r0zLrA?
  twitter_url: https://twitter.com/TheDottGroup
  instagram_url: https://www.instagram.com/thedottrealestategroup/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/TheHonestRealtor/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'East Valley Real Estate Podcast with Aaron Dotterer'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the East Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Dott Real Estate Group - your professional East Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in East Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Aaron Dotterer'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: East Valley Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background1.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0e52c2'
  theme_color: '#6b6b6b'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#264358'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
